image:
  - Visual Studio 2015
  - Ubuntu

environment:
  PERL5LIB: /home/appveyor/perl5/lib/perl5

platform: x64

branches:
  only:
    - master
    - appveyor

skip_tags: true

install:
  - cmd: if not exist "C:\strawberry" cinst strawberryperl
  - cmd: set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cmd: cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - sh: sudo apt-get install build-essential git libssl-dev
  - sh: sudo apt-get install -y perl
  - sh: export PATH=/home/appveyor/perl5/bin:$PATH
  - perl -v
  - cpanm -v Locale::gettext
  - cpanm -v http://search.cpan.org/CPAN/authors/id/R/RA/RAAB/SGMLSpm-1.1.tar.gz
  - cpanm -v Text::WrapI18N
  - cpanm -v Unicode::GCString
  - cpanm -v --installdeps --notest .  

build_script:
  - perl Build.PL
  - ./Build test
