# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         po4a
version:      0.15.4
version_from: lib/Locale/Po4a/TransTractor.pm
installdirs:  site
requires:
    Locale::gettext:               1.01
    SGMLS:                         

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
