--- #YAML:1.0
name: po4a
version: 0.16.3
author:
  - Martin Quinson <martin.quinson@tuxfamily.org>
  - Denis Barbier <barbier@linuxfr.org>
abstract: Tools for helping translation of documentation
license: gpl
requires:
  Locale::gettext: 1.01
  SGMLS: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Locale::Po4a::Chooser:
    file: lib/Locale/Po4a/Chooser.pm
  Locale::Po4a::Dia:
    file: lib/Locale/Po4a/Dia.pm
  Locale::Po4a::KernelHelp:
    file: lib/Locale/Po4a/KernelHelp.pm
  Locale::Po4a::Man:
    file: lib/Locale/Po4a/Man.pm
  Locale::Po4a::Po:
    file: lib/Locale/Po4a/Po.pm
  Locale::Po4a::Pod:
    file: lib/Locale/Po4a/Pod.pm
  Locale::Po4a::Sgml:
    file: lib/Locale/Po4a/Sgml.pm
  Locale::Po4a::TransTractor:
    file: lib/Locale/Po4a/TransTractor.pm
    version: 0.16.3
generated_by: Module::Build version 0.22
